type = "agent"

functions = ["blaxel-search"]
models = ["sandbox-openai"]
agents = []

[entrypoint]
prod = ".venv/bin/python3 -m src"
dev = ".venv/bin/uvicorn src.main:app --reload --port 1338 --host 0.0.0.0 --loop asyncio"

# CopilotKit endpoint trigger
[[triggers]]
id = "copilotkit"
type = "http"
[triggers.configuration]
path = "copilotkit"
authenticationType = ""
retry = 0
