name = "template-copilot-kit-py"
workspace = "amo"
type = "agent"

functions = ["blaxel-search"]
models = ["sandbox-openai"]
agents = []

[entrypoint]
prod = ".venv/bin/python3 -m src"

[env]
DEFAULT_CITY = "Denver"
BL_SERVER_PORT = "80"
BL_SERVER_HOST = "0.0.0.0"

[runtime]
timeout = 300
memory = 1024

# Remove triggers to use default private endpoint only
# The public configuration doesn't seem to work