name = "template-copilot-kit-py"
workspace = "amo"
type = "agent"

functions = ["blaxel-search"]
models = ["sandbox-openai"]
agents = []

[entrypoint]
prod = ".venv/bin/python3 -m src"
dev = ".venv/bin/uvicorn src.main:app --reload --port 1338 --host 0.0.0.0 --loop asyncio"

# Environment variables (non-secrets)
[env]
DEFAULT_CITY = "Denver"
BL_SERVER_PORT = "1338"
BL_SERVER_HOST = "0.0.0.0"

# CopilotKit endpoint trigger
[[triggers]]
id = "copilotkit"
type = "http"
[triggers.configuration]
path = "copilotkit"
authenticationType = ""
retry = 0
